version: "3"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    expose:
    - 5432
    volumes:
      - ./deployments/pg:/docker-entrypoint-initdb.d
    ports:
      - 5433:5432 
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=syncretism
    restart: unless-stopped
  test:
    depends_on:
      - postgres
    build:
      context: ./
    ports:
      - 9000:9000
    volumes:
      - ./:/app
    restart: always 